name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:

    strategy:
      matrix:
        os: [ubuntu-latest, macos-12]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: stable

    - name: Get origin branches
      run: git fetch origin

    - name: Run test
      run: |
        git config --global user.name CI
        git config --global user.email no@email
        make test
